[package]
name = "dpi-test"
version = "0.1.0"
authors = ["kryptan"]
license = "WTFPL"

[dependencies]
glutin = "0.10.0"
gl = "0.6.3"

[patch.crates-io]
winit = { git = "https://github.com/kryptan/winit.git", branch = "win-dpi3" }